name: cloudify
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_acrylic: ^1.0.0+2
  window_manager: ^0.2.7
  system_theme: ^2.0.0
  url_strategy: ^0.2.0
  fluent_ui: ^3.12.0
  provider: ^6.0.3
  carousel_slider: ^4.1.1
  introduction_screen: ^3.0.2
  flutter_image_slideshow: ^0.1.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
